// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: allergy.sql

package sqlcgen

import (
	"context"
)

const getAllergy = `-- name: GetAllergy :one
SELECT "id", "userId", "memberId", "allergenName", "allergyType", "severity", "symptoms", "diagnosedAt", "notes", "createdAt"
FROM "Allergy"
WHERE "id" = $1
`

func (q *Queries) GetAllergy(ctx context.Context, id string) (Allergy, error) {
	row := q.db.QueryRow(ctx, getAllergy, id)
	var i Allergy
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.MemberId,
		&i.AllergenName,
		&i.AllergyType,
		&i.Severity,
		&i.Symptoms,
		&i.DiagnosedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listAllergies = `-- name: ListAllergies :many
SELECT "id", "userId", "memberId", "allergenName", "allergyType", "severity", "symptoms", "diagnosedAt", "notes", "createdAt"
FROM "Allergy"
WHERE "userId" = $1
ORDER BY "createdAt" DESC
`

func (q *Queries) ListAllergies(ctx context.Context, userid string) ([]Allergy, error) {
	rows, err := q.db.Query(ctx, listAllergies, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Allergy{}
	for rows.Next() {
		var i Allergy
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.MemberId,
			&i.AllergenName,
			&i.AllergyType,
			&i.Severity,
			&i.Symptoms,
			&i.DiagnosedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
