// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointment.sql

package sqlcgen

import (
	"context"
)

const getAppointment = `-- name: GetAppointment :one
SELECT "id", "userId", "memberId", "hospitalId", "appointmentType", "appointmentDate", "description", "testResults", "cost", "reminderEnabled", "reminderDaysBefore", "createdAt"
FROM "Appointment"
WHERE "id" = $1
`

func (q *Queries) GetAppointment(ctx context.Context, id string) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.MemberId,
		&i.HospitalId,
		&i.AppointmentType,
		&i.AppointmentDate,
		&i.Description,
		&i.TestResults,
		&i.Cost,
		&i.ReminderEnabled,
		&i.ReminderDaysBefore,
		&i.CreatedAt,
	)
	return i, err
}

const listAppointments = `-- name: ListAppointments :many
SELECT "id", "userId", "memberId", "hospitalId", "appointmentType", "appointmentDate", "description", "testResults", "cost", "reminderEnabled", "reminderDaysBefore", "createdAt"
FROM "Appointment"
WHERE "userId" = $1
ORDER BY "appointmentDate" DESC
`

func (q *Queries) ListAppointments(ctx context.Context, userid string) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointments, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.MemberId,
			&i.HospitalId,
			&i.AppointmentType,
			&i.AppointmentDate,
			&i.Description,
			&i.TestResults,
			&i.Cost,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
