// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: body_measurement.sql

package sqlcgen

import (
	"context"
)

const getBodyMeasurement = `-- name: GetBodyMeasurement :one
SELECT "id", "userId", "memberId", "weight", "height", "recordedAt", "notes", "createdAt"
FROM "BodyMeasurement"
WHERE "id" = $1
`

func (q *Queries) GetBodyMeasurement(ctx context.Context, id string) (BodyMeasurement, error) {
	row := q.db.QueryRow(ctx, getBodyMeasurement, id)
	var i BodyMeasurement
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.MemberId,
		&i.Weight,
		&i.Height,
		&i.RecordedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listBodyMeasurements = `-- name: ListBodyMeasurements :many
SELECT "id", "userId", "memberId", "weight", "height", "recordedAt", "notes", "createdAt"
FROM "BodyMeasurement"
WHERE "userId" = $1
ORDER BY "recordedAt" DESC
`

func (q *Queries) ListBodyMeasurements(ctx context.Context, userid string) ([]BodyMeasurement, error) {
	rows, err := q.db.Query(ctx, listBodyMeasurements, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BodyMeasurement{}
	for rows.Next() {
		var i BodyMeasurement
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.MemberId,
			&i.Weight,
			&i.Height,
			&i.RecordedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
