// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget.sql

package sqlcgen

import (
	"context"
	"time"
)

const getBudgetByUserID = `-- name: GetBudgetByUserID :one
SELECT "id", "userId", "monthlyAmount", "alertEnabled", "lastAlertedMonth", "createdAt", "updatedAt"
FROM "Budget"
WHERE "userId" = $1
`

type GetBudgetByUserIDRow struct {
	ID               string
	UserId           string
	MonthlyAmount    int32
	AlertEnabled     bool
	LastAlertedMonth *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetBudgetByUserID(ctx context.Context, userid string) (GetBudgetByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getBudgetByUserID, userid)
	var i GetBudgetByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.MonthlyAmount,
		&i.AlertEnabled,
		&i.LastAlertedMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoryBudgets = `-- name: ListCategoryBudgets :many
SELECT "category", "monthlyAmount"
FROM "CategoryBudget"
WHERE "userId" = $1
ORDER BY "category"
`

type ListCategoryBudgetsRow struct {
	Category      string
	MonthlyAmount int32
}

func (q *Queries) ListCategoryBudgets(ctx context.Context, userid string) ([]ListCategoryBudgetsRow, error) {
	rows, err := q.db.Query(ctx, listCategoryBudgets, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoryBudgetsRow{}
	for rows.Next() {
		var i ListCategoryBudgetsRow
		if err := rows.Scan(&i.Category, &i.MonthlyAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
