// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard_preference.sql

package sqlcgen

import (
	"context"
)

const getDashboardPreference = `-- name: GetDashboardPreference :one
SELECT "userId", "hiddenCards", "cardOrder", "defaultMemberId"
FROM "DashboardPreference"
WHERE "userId" = $1
`

type GetDashboardPreferenceRow struct {
	UserId          string
	HiddenCards     []string
	CardOrder       []string
	DefaultMemberId *string
}

func (q *Queries) GetDashboardPreference(ctx context.Context, userid string) (GetDashboardPreferenceRow, error) {
	row := q.db.QueryRow(ctx, getDashboardPreference, userid)
	var i GetDashboardPreferenceRow
	err := row.Scan(
		&i.UserId,
		&i.HiddenCards,
		&i.CardOrder,
		&i.DefaultMemberId,
	)
	return i, err
}
