// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emergency_contact.sql

package sqlcgen

import (
	"context"
)

const getEmergencyContact = `-- name: GetEmergencyContact :one
SELECT "id", "userId", "memberId", "contactName", "phoneNumber", "relationship", "notes", "createdAt"
FROM "EmergencyContact"
WHERE "id" = $1
`

func (q *Queries) GetEmergencyContact(ctx context.Context, id string) (EmergencyContact, error) {
	row := q.db.QueryRow(ctx, getEmergencyContact, id)
	var i EmergencyContact
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.MemberId,
		&i.ContactName,
		&i.PhoneNumber,
		&i.Relationship,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listEmergencyContacts = `-- name: ListEmergencyContacts :many
SELECT "id", "userId", "memberId", "contactName", "phoneNumber", "relationship", "notes", "createdAt"
FROM "EmergencyContact"
WHERE "userId" = $1
ORDER BY "createdAt" DESC
`

func (q *Queries) ListEmergencyContacts(ctx context.Context, userid string) ([]EmergencyContact, error) {
	rows, err := q.db.Query(ctx, listEmergencyContacts, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmergencyContact{}
	for rows.Next() {
		var i EmergencyContact
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.MemberId,
			&i.ContactName,
			&i.PhoneNumber,
			&i.Relationship,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
