// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: examination.sql

package sqlcgen

import (
	"context"
)

const getExamination = `-- name: GetExamination :one
SELECT "id", "userId", "memberId", "examinationType", "examinedAt", "nextScheduledDate", "notes", "imageData", "createdAt"
FROM "Examination"
WHERE "id" = $1
`

func (q *Queries) GetExamination(ctx context.Context, id string) (Examination, error) {
	row := q.db.QueryRow(ctx, getExamination, id)
	var i Examination
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.MemberId,
		&i.ExaminationType,
		&i.ExaminedAt,
		&i.NextScheduledDate,
		&i.Notes,
		&i.ImageData,
		&i.CreatedAt,
	)
	return i, err
}

const listExaminations = `-- name: ListExaminations :many
SELECT "id", "userId", "memberId", "examinationType", "examinedAt", "nextScheduledDate", "notes", "imageData", "createdAt"
FROM "Examination"
WHERE "userId" = $1
ORDER BY "examinedAt" DESC
`

func (q *Queries) ListExaminations(ctx context.Context, userid string) ([]Examination, error) {
	rows, err := q.db.Query(ctx, listExaminations, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Examination{}
	for rows.Next() {
		var i Examination
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.MemberId,
			&i.ExaminationType,
			&i.ExaminedAt,
			&i.NextScheduledDate,
			&i.Notes,
			&i.ImageData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
