// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense.sql

package sqlcgen

import (
	"context"
)

const getExpense = `-- name: GetExpense :one
SELECT "id", "userId", "memberId", "category", "amount", "description", "expenseDate", "isDeductible", "createdAt"
FROM "Expense"
WHERE "id" = $1
`

func (q *Queries) GetExpense(ctx context.Context, id string) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpense, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.MemberId,
		&i.Category,
		&i.Amount,
		&i.Description,
		&i.ExpenseDate,
		&i.IsDeductible,
		&i.CreatedAt,
	)
	return i, err
}
