// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health_log.sql

package sqlcgen

import (
	"context"
)

const getHealthLog = `-- name: GetHealthLog :one
SELECT "id", "memberId", "userId", "conditionLevel", "symptoms", "notes", "recordedAt"
FROM "HealthLog"
WHERE "id" = $1
`

func (q *Queries) GetHealthLog(ctx context.Context, id string) (HealthLog, error) {
	row := q.db.QueryRow(ctx, getHealthLog, id)
	var i HealthLog
	err := row.Scan(
		&i.ID,
		&i.MemberId,
		&i.UserId,
		&i.ConditionLevel,
		&i.Symptoms,
		&i.Notes,
		&i.RecordedAt,
	)
	return i, err
}

const listHealthLogs = `-- name: ListHealthLogs :many
SELECT "id", "memberId", "userId", "conditionLevel", "symptoms", "notes", "recordedAt"
FROM "HealthLog"
WHERE "userId" = $1
ORDER BY "recordedAt" DESC
`

func (q *Queries) ListHealthLogs(ctx context.Context, userid string) ([]HealthLog, error) {
	rows, err := q.db.Query(ctx, listHealthLogs, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HealthLog{}
	for rows.Next() {
		var i HealthLog
		if err := rows.Scan(
			&i.ID,
			&i.MemberId,
			&i.UserId,
			&i.ConditionLevel,
			&i.Symptoms,
			&i.Notes,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
