// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hospital.sql

package sqlcgen

import (
	"context"
)

const getHospital = `-- name: GetHospital :one
SELECT "id", "userId", "name", "hospitalType", "address", "phoneNumber", "department", "doctorName", "notes", "createdAt"
FROM "Hospital"
WHERE "id" = $1
`

func (q *Queries) GetHospital(ctx context.Context, id string) (Hospital, error) {
	row := q.db.QueryRow(ctx, getHospital, id)
	var i Hospital
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Name,
		&i.HospitalType,
		&i.Address,
		&i.PhoneNumber,
		&i.Department,
		&i.DoctorName,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listHospitals = `-- name: ListHospitals :many
SELECT "id", "userId", "name", "hospitalType", "address", "phoneNumber", "department", "doctorName", "notes", "createdAt"
FROM "Hospital"
WHERE "userId" = $1
ORDER BY "createdAt" DESC
`

func (q *Queries) ListHospitals(ctx context.Context, userid string) ([]Hospital, error) {
	rows, err := q.db.Query(ctx, listHospitals, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hospital{}
	for rows.Next() {
		var i Hospital
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.Name,
			&i.HospitalType,
			&i.Address,
			&i.PhoneNumber,
			&i.Department,
			&i.DoctorName,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
