// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insurance.sql

package sqlcgen

import (
	"context"
)

const getInsurance = `-- name: GetInsurance :one
SELECT "id", "userId", "memberId", "insuranceType", "providerName", "policyNumber", "notes", "createdAt"
FROM "Insurance"
WHERE "id" = $1
`

func (q *Queries) GetInsurance(ctx context.Context, id string) (Insurance, error) {
	row := q.db.QueryRow(ctx, getInsurance, id)
	var i Insurance
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.MemberId,
		&i.InsuranceType,
		&i.ProviderName,
		&i.PolicyNumber,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listInsurances = `-- name: ListInsurances :many
SELECT "id", "userId", "memberId", "insuranceType", "providerName", "policyNumber", "notes", "createdAt"
FROM "Insurance"
WHERE "userId" = $1
ORDER BY "createdAt" DESC
`

func (q *Queries) ListInsurances(ctx context.Context, userid string) ([]Insurance, error) {
	rows, err := q.db.Query(ctx, listInsurances, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Insurance{}
	for rows.Next() {
		var i Insurance
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.MemberId,
			&i.InsuranceType,
			&i.ProviderName,
			&i.PolicyNumber,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
