// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: medication.sql

package sqlcgen

import (
	"context"
)

const getMedication = `-- name: GetMedication :one
SELECT "id", "memberId", "userId", "name", "category", "dosageAmount", "frequency",
       "stockQuantity", "stockAlertDate", "intervalHours", "instructions", "displayOrder",
       "isActive", "status", "createdAt", "updatedAt"
FROM "Medication"
WHERE "id" = $1
`

func (q *Queries) GetMedication(ctx context.Context, id string) (Medication, error) {
	row := q.db.QueryRow(ctx, getMedication, id)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.MemberId,
		&i.UserId,
		&i.Name,
		&i.Category,
		&i.DosageAmount,
		&i.Frequency,
		&i.StockQuantity,
		&i.StockAlertDate,
		&i.IntervalHours,
		&i.Instructions,
		&i.DisplayOrder,
		&i.IsActive,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMedicationsByMember = `-- name: ListMedicationsByMember :many
SELECT "id", "memberId", "userId", "name", "category", "dosageAmount", "frequency",
       "stockQuantity", "stockAlertDate", "intervalHours", "instructions", "displayOrder",
       "isActive", "status", "createdAt", "updatedAt"
FROM "Medication"
WHERE "memberId" = $1
ORDER BY "displayOrder" ASC, "createdAt" ASC
`

func (q *Queries) ListMedicationsByMember(ctx context.Context, memberid string) ([]Medication, error) {
	rows, err := q.db.Query(ctx, listMedicationsByMember, memberid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medication{}
	for rows.Next() {
		var i Medication
		if err := rows.Scan(
			&i.ID,
			&i.MemberId,
			&i.UserId,
			&i.Name,
			&i.Category,
			&i.DosageAmount,
			&i.Frequency,
			&i.StockQuantity,
			&i.StockAlertDate,
			&i.IntervalHours,
			&i.Instructions,
			&i.DisplayOrder,
			&i.IsActive,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedicationsByUser = `-- name: ListMedicationsByUser :many
SELECT "id", "memberId", "userId", "name", "category", "dosageAmount", "frequency",
       "stockQuantity", "stockAlertDate", "intervalHours", "instructions", "displayOrder",
       "isActive", "status", "createdAt", "updatedAt"
FROM "Medication"
WHERE "userId" = $1
ORDER BY "displayOrder" ASC, "createdAt" ASC
`

func (q *Queries) ListMedicationsByUser(ctx context.Context, userid string) ([]Medication, error) {
	rows, err := q.db.Query(ctx, listMedicationsByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medication{}
	for rows.Next() {
		var i Medication
		if err := rows.Scan(
			&i.ID,
			&i.MemberId,
			&i.UserId,
			&i.Name,
			&i.Category,
			&i.DosageAmount,
			&i.Frequency,
			&i.StockQuantity,
			&i.StockAlertDate,
			&i.IntervalHours,
			&i.Instructions,
			&i.DisplayOrder,
			&i.IsActive,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
