// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: medication_record.sql

package sqlcgen

import (
	"context"
)

const getMedicationRecord = `-- name: GetMedicationRecord :one
SELECT "id", "memberId", "medicationId", "userId", "scheduleId", "takenAt", "notes", "dosageAmount"
FROM "MedicationRecord"
WHERE "id" = $1
`

func (q *Queries) GetMedicationRecord(ctx context.Context, id string) (MedicationRecord, error) {
	row := q.db.QueryRow(ctx, getMedicationRecord, id)
	var i MedicationRecord
	err := row.Scan(
		&i.ID,
		&i.MemberId,
		&i.MedicationId,
		&i.UserId,
		&i.ScheduleId,
		&i.TakenAt,
		&i.Notes,
		&i.DosageAmount,
	)
	return i, err
}

const listMedicationRecordsByMember = `-- name: ListMedicationRecordsByMember :many
SELECT "id", "memberId", "medicationId", "userId", "scheduleId", "takenAt", "notes", "dosageAmount"
FROM "MedicationRecord"
WHERE "memberId" = $1
ORDER BY "takenAt" DESC
`

func (q *Queries) ListMedicationRecordsByMember(ctx context.Context, memberid string) ([]MedicationRecord, error) {
	rows, err := q.db.Query(ctx, listMedicationRecordsByMember, memberid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationRecord{}
	for rows.Next() {
		var i MedicationRecord
		if err := rows.Scan(
			&i.ID,
			&i.MemberId,
			&i.MedicationId,
			&i.UserId,
			&i.ScheduleId,
			&i.TakenAt,
			&i.Notes,
			&i.DosageAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedicationRecordsByUser = `-- name: ListMedicationRecordsByUser :many
SELECT "id", "memberId", "medicationId", "userId", "scheduleId", "takenAt", "notes", "dosageAmount"
FROM "MedicationRecord"
WHERE "userId" = $1
ORDER BY "takenAt" DESC
`

func (q *Queries) ListMedicationRecordsByUser(ctx context.Context, userid string) ([]MedicationRecord, error) {
	rows, err := q.db.Query(ctx, listMedicationRecordsByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationRecord{}
	for rows.Next() {
		var i MedicationRecord
		if err := rows.Scan(
			&i.ID,
			&i.MemberId,
			&i.MedicationId,
			&i.UserId,
			&i.ScheduleId,
			&i.TakenAt,
			&i.Notes,
			&i.DosageAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
