// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: member.sql

package sqlcgen

import (
	"context"
)

const getMember = `-- name: GetMember :one
SELECT "id", "userId", "memberType", "name", "petType", "photoUrl", "birthDate", "notes", "createdAt", "updatedAt"
FROM "Member"
WHERE "id" = $1
`

func (q *Queries) GetMember(ctx context.Context, id string) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.MemberType,
		&i.Name,
		&i.PetType,
		&i.PhotoUrl,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT "id", "userId", "memberType", "name", "petType", "photoUrl", "birthDate", "notes", "createdAt", "updatedAt"
FROM "Member"
WHERE "userId" = $1
ORDER BY "createdAt" ASC
`

func (q *Queries) ListMembers(ctx context.Context, userid string) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.MemberType,
			&i.Name,
			&i.PetType,
			&i.PhotoUrl,
			&i.BirthDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
