// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"
)

type Allergy struct {
	ID           string
	UserId       string
	MemberId     string
	AllergenName string
	AllergyType  string
	Severity     string
	Symptoms     *string
	DiagnosedAt  *time.Time
	Notes        *string
	CreatedAt    time.Time
}

type Appointment struct {
	ID                 string
	UserId             string
	MemberId           string
	HospitalId         *string
	AppointmentType    *string
	AppointmentDate    time.Time
	Description        *string
	TestResults        *string
	Cost               *float64
	ReminderEnabled    bool
	ReminderDaysBefore int32
	CreatedAt          time.Time
}

type BodyMeasurement struct {
	ID         string
	UserId     string
	MemberId   string
	Weight     *float64
	Height     *float64
	RecordedAt time.Time
	Notes      *string
	CreatedAt  time.Time
}

type Budget struct {
	ID               string
	UserId           string
	MonthlyAmount    int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	AlertEnabled     bool
	LastAlertedMonth *string
}

type CategoryBudget struct {
	ID            string
	UserId        string
	Category      string
	MonthlyAmount int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type DashboardPreference struct {
	ID              string
	UserId          string
	HiddenCards     []string
	CardOrder       []string
	DefaultMemberId *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type EmergencyContact struct {
	ID           string
	UserId       string
	MemberId     string
	ContactName  string
	PhoneNumber  string
	Relationship *string
	Notes        *string
	CreatedAt    time.Time
}

type Examination struct {
	ID                string
	UserId            string
	MemberId          string
	ExaminationType   string
	ExaminedAt        time.Time
	NextScheduledDate *time.Time
	Notes             *string
	ImageData         *string
	CreatedAt         time.Time
}

type Expense struct {
	ID           string
	UserId       string
	MemberId     *string
	Category     string
	Amount       int32
	Description  *string
	ExpenseDate  time.Time
	IsDeductible bool
	CreatedAt    time.Time
}

type HealthLog struct {
	ID             string
	MemberId       string
	UserId         string
	ConditionLevel int32
	Symptoms       []string
	Notes          *string
	RecordedAt     time.Time
}

type Hospital struct {
	ID           string
	UserId       string
	Name         string
	HospitalType *string
	Address      *string
	PhoneNumber  *string
	Department   *string
	DoctorName   *string
	Notes        *string
	CreatedAt    time.Time
}

type Insurance struct {
	ID            string
	UserId        string
	MemberId      string
	InsuranceType string
	ProviderName  *string
	PolicyNumber  *string
	Notes         *string
	CreatedAt     time.Time
}

type Medication struct {
	ID             string
	MemberId       string
	UserId         string
	Name           string
	Category       string
	DosageAmount   *string
	Frequency      *string
	StockQuantity  *int32
	StockAlertDate *time.Time
	IntervalHours  *int32
	Instructions   *string
	DisplayOrder   int32
	IsActive       bool
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type MedicationRecord struct {
	ID           string
	MemberId     string
	MedicationId string
	UserId       string
	ScheduleId   *string
	TakenAt      time.Time
	Notes        *string
	DosageAmount *string
}

type Member struct {
	ID         string
	UserId     string
	MemberType string
	Name       string
	PetType    *string
	PhotoUrl   *string
	BirthDate  *time.Time
	Notes      *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type NotificationSetting struct {
	ID                                   string
	UserId                               string
	MedicationReminderEnabled            bool
	MissedMedicationEnabled              bool
	AppointmentReminderEnabled           bool
	LowStockAlertEnabled                 bool
	DefaultReminderMinutesBefore         int32
	DefaultAppointmentReminderDaysBefore int32
	EmailNotificationEnabled             bool
	CreatedAt                            time.Time
	UpdatedAt                            time.Time
}

type Prescription struct {
	ID               string
	UserId           string
	MemberId         string
	PrescriptionName string
	PrescribedBy     *string
	PrescribedAt     time.Time
	ExpiresAt        *time.Time
	PharmacyName     *string
	Notes            *string
	CreatedAt        time.Time
	ElectronicCode   *string
}

type PrescriptionItem struct {
	ID             string
	PrescriptionId string
	Name           string
	Dosage         *string
	Frequency      *string
	Days           *int32
	SortOrder      int32
	CreatedAt      time.Time
}

type Schedule struct {
	ID                    string
	MedicationId          string
	UserId                string
	MemberId              string
	ScheduledTime         string
	DaysOfWeek            []string
	IntervalDays          *int32
	StartDate             *time.Time
	IsEnabled             bool
	ReminderMinutesBefore int32
	CreatedAt             time.Time
}

type TemperatureRecord struct {
	ID          string
	UserId      string
	MemberId    string
	Temperature float64
	MeasuredAt  time.Time
	Notes       *string
	CreatedAt   time.Time
}

type User struct {
	ID                   string
	Email                string
	Password             string
	DisplayName          *string
	CharacterType        string
	CharacterName        *string
	EmailVerified        bool
	VerificationCode     *string
	VerificationExpiry   *time.Time
	VerificationAttempts int32
	ResetCode            *string
	ResetCodeExpiry      *time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	GoogleId             *string
	ResetAttempts        int32
}

type Vaccination struct {
	ID                string
	UserId            string
	MemberId          string
	VaccineName       string
	VaccinatedAt      time.Time
	NextScheduledDate *time.Time
	Notes             *string
	CreatedAt         time.Time
}
