// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_setting.sql

package sqlcgen

import (
	"context"
)

const getNotificationSettingByUserID = `-- name: GetNotificationSettingByUserID :one
SELECT "id", "userId", "medicationReminderEnabled", "missedMedicationEnabled",
       "appointmentReminderEnabled", "lowStockAlertEnabled", "defaultReminderMinutesBefore",
       "defaultAppointmentReminderDaysBefore", "emailNotificationEnabled", "createdAt", "updatedAt"
FROM "NotificationSetting"
WHERE "userId" = $1
`

func (q *Queries) GetNotificationSettingByUserID(ctx context.Context, userid string) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, getNotificationSettingByUserID, userid)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.MedicationReminderEnabled,
		&i.MissedMedicationEnabled,
		&i.AppointmentReminderEnabled,
		&i.LowStockAlertEnabled,
		&i.DefaultReminderMinutesBefore,
		&i.DefaultAppointmentReminderDaysBefore,
		&i.EmailNotificationEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
