// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prescription.sql

package sqlcgen

import (
	"context"
	"time"
)

const getPrescription = `-- name: GetPrescription :one
SELECT "id", "userId", "memberId", "prescriptionName", "prescribedBy", "prescribedAt", "expiresAt", "pharmacyName", "electronicCode", "notes", "createdAt"
FROM "Prescription"
WHERE "id" = $1
`

type GetPrescriptionRow struct {
	ID               string
	UserId           string
	MemberId         string
	PrescriptionName string
	PrescribedBy     *string
	PrescribedAt     time.Time
	ExpiresAt        *time.Time
	PharmacyName     *string
	ElectronicCode   *string
	Notes            *string
	CreatedAt        time.Time
}

func (q *Queries) GetPrescription(ctx context.Context, id string) (GetPrescriptionRow, error) {
	row := q.db.QueryRow(ctx, getPrescription, id)
	var i GetPrescriptionRow
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.MemberId,
		&i.PrescriptionName,
		&i.PrescribedBy,
		&i.PrescribedAt,
		&i.ExpiresAt,
		&i.PharmacyName,
		&i.ElectronicCode,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listPrescriptionItems = `-- name: ListPrescriptionItems :many
SELECT "id", "prescriptionId", "name", "dosage", "frequency", "days", "sortOrder"
FROM "PrescriptionItem"
WHERE "prescriptionId" = $1
ORDER BY "sortOrder", "createdAt"
`

type ListPrescriptionItemsRow struct {
	ID             string
	PrescriptionId string
	Name           string
	Dosage         *string
	Frequency      *string
	Days           *int32
	SortOrder      int32
}

func (q *Queries) ListPrescriptionItems(ctx context.Context, prescriptionid string) ([]ListPrescriptionItemsRow, error) {
	rows, err := q.db.Query(ctx, listPrescriptionItems, prescriptionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrescriptionItemsRow{}
	for rows.Next() {
		var i ListPrescriptionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PrescriptionId,
			&i.Name,
			&i.Dosage,
			&i.Frequency,
			&i.Days,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
