// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule.sql

package sqlcgen

import (
	"context"
)

const getSchedule = `-- name: GetSchedule :one
SELECT "id", "medicationId", "userId", "memberId", "scheduledTime", "daysOfWeek",
       "intervalDays", "startDate", "isEnabled", "reminderMinutesBefore", "createdAt"
FROM "Schedule"
WHERE "id" = $1
`

func (q *Queries) GetSchedule(ctx context.Context, id string) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.MedicationId,
		&i.UserId,
		&i.MemberId,
		&i.ScheduledTime,
		&i.DaysOfWeek,
		&i.IntervalDays,
		&i.StartDate,
		&i.IsEnabled,
		&i.ReminderMinutesBefore,
		&i.CreatedAt,
	)
	return i, err
}

const listSchedulesByUser = `-- name: ListSchedulesByUser :many
SELECT "id", "medicationId", "userId", "memberId", "scheduledTime", "daysOfWeek",
       "intervalDays", "startDate", "isEnabled", "reminderMinutesBefore", "createdAt"
FROM "Schedule"
WHERE "userId" = $1
ORDER BY "scheduledTime" ASC
`

func (q *Queries) ListSchedulesByUser(ctx context.Context, userid string) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.MedicationId,
			&i.UserId,
			&i.MemberId,
			&i.ScheduledTime,
			&i.DaysOfWeek,
			&i.IntervalDays,
			&i.StartDate,
			&i.IsEnabled,
			&i.ReminderMinutesBefore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
