// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: temperature_record.sql

package sqlcgen

import (
	"context"
)

const getTemperatureRecord = `-- name: GetTemperatureRecord :one
SELECT "id", "userId", "memberId", "temperature", "measuredAt", "notes", "createdAt"
FROM "TemperatureRecord"
WHERE "id" = $1
`

func (q *Queries) GetTemperatureRecord(ctx context.Context, id string) (TemperatureRecord, error) {
	row := q.db.QueryRow(ctx, getTemperatureRecord, id)
	var i TemperatureRecord
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.MemberId,
		&i.Temperature,
		&i.MeasuredAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listTemperatureRecords = `-- name: ListTemperatureRecords :many
SELECT "id", "userId", "memberId", "temperature", "measuredAt", "notes", "createdAt"
FROM "TemperatureRecord"
WHERE "userId" = $1
ORDER BY "measuredAt" DESC
`

func (q *Queries) ListTemperatureRecords(ctx context.Context, userid string) ([]TemperatureRecord, error) {
	rows, err := q.db.Query(ctx, listTemperatureRecords, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemperatureRecord{}
	for rows.Next() {
		var i TemperatureRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.MemberId,
			&i.Temperature,
			&i.MeasuredAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemperatureRecordsByMember = `-- name: ListTemperatureRecordsByMember :many
SELECT "id", "userId", "memberId", "temperature", "measuredAt", "notes", "createdAt"
FROM "TemperatureRecord"
WHERE "memberId" = $1
ORDER BY "measuredAt" DESC
`

func (q *Queries) ListTemperatureRecordsByMember(ctx context.Context, memberid string) ([]TemperatureRecord, error) {
	rows, err := q.db.Query(ctx, listTemperatureRecordsByMember, memberid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemperatureRecord{}
	for rows.Next() {
		var i TemperatureRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.MemberId,
			&i.Temperature,
			&i.MeasuredAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
