// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlcgen

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT "id", "email", "password", "displayName", "characterType", "characterName",
       "emailVerified", "verificationCode", "verificationExpiry", "verificationAttempts",
       "resetCode", "resetCodeExpiry", "createdAt", "updatedAt", "googleId", "resetAttempts"
FROM "User"
WHERE "email" = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.DisplayName,
		&i.CharacterType,
		&i.CharacterName,
		&i.EmailVerified,
		&i.VerificationCode,
		&i.VerificationExpiry,
		&i.VerificationAttempts,
		&i.ResetCode,
		&i.ResetCodeExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleId,
		&i.ResetAttempts,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT "id", "email", "password", "displayName", "characterType", "characterName",
       "emailVerified", "verificationCode", "verificationExpiry", "verificationAttempts",
       "resetCode", "resetCodeExpiry", "createdAt", "updatedAt", "googleId", "resetAttempts"
FROM "User"
WHERE "googleId" = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleid *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.DisplayName,
		&i.CharacterType,
		&i.CharacterName,
		&i.EmailVerified,
		&i.VerificationCode,
		&i.VerificationExpiry,
		&i.VerificationAttempts,
		&i.ResetCode,
		&i.ResetCodeExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleId,
		&i.ResetAttempts,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT "id", "email", "password", "displayName", "characterType", "characterName",
       "emailVerified", "verificationCode", "verificationExpiry", "verificationAttempts",
       "resetCode", "resetCodeExpiry", "createdAt", "updatedAt", "googleId", "resetAttempts"
FROM "User"
WHERE "id" = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.DisplayName,
		&i.CharacterType,
		&i.CharacterName,
		&i.EmailVerified,
		&i.VerificationCode,
		&i.VerificationExpiry,
		&i.VerificationAttempts,
		&i.ResetCode,
		&i.ResetCodeExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleId,
		&i.ResetAttempts,
	)
	return i, err
}
