// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vaccination.sql

package sqlcgen

import (
	"context"
)

const getVaccination = `-- name: GetVaccination :one
SELECT "id", "userId", "memberId", "vaccineName", "vaccinatedAt", "nextScheduledDate", "notes", "createdAt"
FROM "Vaccination"
WHERE "id" = $1
`

func (q *Queries) GetVaccination(ctx context.Context, id string) (Vaccination, error) {
	row := q.db.QueryRow(ctx, getVaccination, id)
	var i Vaccination
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.MemberId,
		&i.VaccineName,
		&i.VaccinatedAt,
		&i.NextScheduledDate,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listVaccinations = `-- name: ListVaccinations :many
SELECT "id", "userId", "memberId", "vaccineName", "vaccinatedAt", "nextScheduledDate", "notes", "createdAt"
FROM "Vaccination"
WHERE "userId" = $1
ORDER BY "vaccinatedAt" DESC
`

func (q *Queries) ListVaccinations(ctx context.Context, userid string) ([]Vaccination, error) {
	rows, err := q.db.Query(ctx, listVaccinations, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vaccination{}
	for rows.Next() {
		var i Vaccination
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.MemberId,
			&i.VaccineName,
			&i.VaccinatedAt,
			&i.NextScheduledDate,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
